<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Alis-MacBook-Pro.local" failures="1" tests="3" name="Opening Facebook Landing Page" time="13.662" errors="0" timestamp="3 Apr 2019 19:45:11 GMT">
  <testcase classname="testcases.FB_LandingPage_Test" name="Login" time="4.885"/>
  <testcase classname="testcases.FB_LandingPage_Test" name="Login" time="1.497">
    <failure type="java.lang.AssertionError" message="Test2 expected [This test will fail] but found [Share what&amp;apos;s new]">
      <![CDATA[java.lang.AssertionError: Test2 expected [This test will fail] but found [Share what's new]
	at testcases.FB_LandingPage_Test.Login(FB_LandingPage_Test.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Login -->
  <testcase classname="testcases.FB_LandingPage_Test" name="Login" time="3.049"/>
</testsuite> <!-- Opening Facebook Landing Page -->
