# Created at 2019-04-02T17:32:57.894
TestSet has not finished before stream error has appeared >> initializing exit by non-null configuration: DEFAULT
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:397)
	at org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
	at org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:390)
	at java.base/java.lang.Thread.run(Thread.java:834)


# Created at 2019-04-02T17:32:57.904
Unexpected IOException: 8,1,testcases.SignUpPage_Login_Test,LoginToAccount(testcases.SignUpPage_Login_Test),null,java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:37913\000ABuild info: version: '3.141.59'\002C revision: 'e82be7d358'\002C time: '2018-11-14T08:17:03'\000ASystem info: host: 'Alis-MacBook-Pro.local'\002C ip: '192.168.1.7'\002C os.name: 'Mac OS X'\002C os.arch: 'x86_64'\002C os.version: '10.14.3'\002C java.version: '11.0.2'\000ADriver info: driver.version: RemoteWebDriver,null,java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:37913\000ABuild info: version: '3.141.59'\002C revision: 'e82be7d358'\002C time: '2018-11-14T08:17:03'\000ASystem info: host: 'Alis-MacBook-Pro.local'\002C ip: '192.168.1.7'\002C os.name: 'Mac OS X'\002C os.arch: 'x86_64'\002C os.version: '10.14.3'\002C java.version: '11.0.2'\000ADriver info: driver.version: RemoteWebDriver,SignUpPage_Login_Test.LoginToAccount:31 \00BB WebDriver java.net.ConnectException:...,org.openqa.selenium.WebDriverException: \000Ajava.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:37913\000ABuild info: version: '3.141.59'\002C revision: 'e82be7d358'\002C time: '2018-11-14T08:17:03'\000ASystem info: host: 'Alis-MacBook-Pro.local'\002C ip: '192.168.1.7'\002C os.name: 'Mac OS X'\002C os.arch: 'x86_64'\002C os.version: '10.14.3'\002C java.version: '11.0.2'\000ADriver info: driver.version: RemoteWebDriver\000A\0009at testcases.SignUpPage_Login_Test.LoginToAccount(SignUpPage_Login_Test.java:31)\000ACaused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:37913\000A\0009at testcases.SignUpPage_Login_Test.LoginToAccount(SignUpPage_Login_Test.java:31)\000ACaused by: java.net.ConnectException: Connection refused (Connection refused)\000A\0009at testcases.SignUpPage_Login_Test.LoginToAccount(SignUpPage_Login_Test.java:31)\000A


